version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Logging in to CodeArtifact..."
      # Replace 123456789012 with your real AWS Account ID
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 123456789012 --region us-east-1 --query authorizationToken --output text)
  build:
    commands:
      - echo "Building War file..."
      - mvn clean install
artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no