version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Logging into Amazon CodeArtifact..."
      # Make sure the next line is exactly like this (using your account ID)
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 925661928665 --query authorizationToken --output text)
      - echo "====== BEGINNING TEST PHASE ======"
      - chmod +x run-tests.sh
      - ./run-tests.sh
  build:
    commands:
      - echo "====== BEGINNING BUILD PHASE ======"
      - mvn -s settings.xml compile
      - mvn -s settings.xml package
artifacts:
  files:
    - target/*.war
  discard-paths: yes